In [41]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [42]:
train=pd.read_csv(r"Downloads\train_upd.csv")

In [43]:
train.describe()

,cell_name,4G_rat,par_year,par_month,par_day,par_hour,par_min,subscriber_count,web_browsing_total_bytes,video_total_bytes,...,voip_total_bytes,speedtest_total_bytes,email_total_bytes,weather_total_bytes,media_total_bytes,mms_total_bytes,others_total_bytes,beam_direction,cell_range,tilt
count,7.856000e+04,78560.000000,78560.0,78560.0,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,...,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000
mean,2.785900e+09,0.499173,2018.0,12.0,15.503831,11.514588,33.061736,571.187131,8091.673002,8293.335871,...,70.619539,70.689779,70.987156,70.945481,70.594857,70.719297,69.728182,89.991701,4.492146,3.503055
std,1.604667e+09,0.500002,0.0,0.0,8.634375,6.934351,16.535863,1080.263507,19145.523831,19462.783122,...,117.255264,118.102336,117.821916,117.134609,117.647164,118.032907,114.619303,17.638370,1.709296,1.115255
min,8.737700e+04,0.000000,2018.0,12.0,1.000000,0.000000,5.000000,1.000000,3.000000,5.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,60.000000,2.000000,2.000000
25%,1.395260e+09,0.000000,2018.0,12.0,8.000000,5.000000,20.000000,71.000000,431.000000,471.000000,...,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,75.000000,3.000000,3.000000
50%,2.786354e+09,0.000000,2018.0,12.0,16.000000,12.000000,35.000000,187.000000,1545.500000,1672.500000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,90.000000,4.000000,4.000000
75%,4.172220e+09,1.000000,2018.0,12.0,23.000000,18.000000,45.000000,568.000000,6565.000000,6884.250000,...,75.000000,75.000000,75.000000,76.000000,74.000000,75.000000,75.000000,105.000000,6.000000,4.000000
max,5.555540e+09,1.000000,2018.0,12.0,30.000000,23.000000,60.000000,16570.000000,311008.000000,331271.000000,...,1560.000000,1612.000000,1563.000000,1680.000000,1661.000000,1611.000000,1600.000000,120.000000,7.000000,5.000000

In [44]:
train.head()

,cell_name,4G_rat,par_year,par_month,par_day,par_hour,par_min,subscriber_count,web_browsing_total_bytes,video_total_bytes,...,email_total_bytes,weather_total_bytes,media_total_bytes,mms_total_bytes,others_total_bytes,beam_direction,cell_range,tilt,ran_vendor,Congestion_Type
0,1090595862,1,2018,12,15,0,50,152,315,59012,...,10,33,46,39,103,69,6,2,ERICSSON,4G_BACKHAUL_CONGESTION
1,4826375369,1,2018,12,7,20,5,54,1871,334,...,22,20,7,10,21,93,7,5,NOKIA,NC
2,3607540856,1,2018,12,5,16,35,277,887,945,...,14,91,49,147,159,77,6,3,ERICSSON,3G_BACKHAUL_CONGESTION
3,1245076813,0,2018,12,16,21,60,51,8577,494,...,10,63,42,75,35,95,7,2,HUAWEI,3G_BACKHAUL_CONGESTION
4,404129745,1,2018,12,4,6,60,117,2084,1056,...,67,59,91,197,316,112,3,5,HUAWEI,4G_RAN_CONGESTION

In [45]:
train=train.drop(['ran_vendor'],axis=1)

In [46]:
train.head()

,cell_name,4G_rat,par_year,par_month,par_day,par_hour,par_min,subscriber_count,web_browsing_total_bytes,video_total_bytes,...,speedtest_total_bytes,email_total_bytes,weather_total_bytes,media_total_bytes,mms_total_bytes,others_total_bytes,beam_direction,cell_range,tilt,Congestion_Type
0,1090595862,1,2018,12,15,0,50,152,315,59012,...,10,10,33,46,39,103,69,6,2,4G_BACKHAUL_CONGESTION
1,4826375369,1,2018,12,7,20,5,54,1871,334,...,8,22,20,7,10,21,93,7,5,NC
2,3607540856,1,2018,12,5,16,35,277,887,945,...,23,14,91,49,147,159,77,6,3,3G_BACKHAUL_CONGESTION
3,1245076813,0,2018,12,16,21,60,51,8577,494,...,3,10,63,42,75,35,95,7,2,3G_BACKHAUL_CONGESTION
4,404129745,1,2018,12,4,6,60,117,2084,1056,...,4,67,59,91,197,316,112,3,5,4G_RAN_CONGESTION

In [47]:
from sklearn.preprocessing import LabelEncoder as le
a= train['Congestion_Type']
le = le()

In [48]:
label = le.fit_transform(a)
df = pd.DataFrame(label)
train = train.drop(['Congestion_Type'],axis=1)
train = pd.concat([train,df],axis=1)
train['Congestion_Type']=train[0] 
train = train.drop([0],axis=1)

In [49]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78560 entries, 0 to 78559
Data columns (total 38 columns):
cell_name                        78560 non-null int64
4G_rat                           78560 non-null int64
par_year                         78560 non-null int64
par_month                        78560 non-null int64
par_day                          78560 non-null int64
par_hour                         78560 non-null int64
par_min                          78560 non-null int64
subscriber_count                 78560 non-null int64
web_browsing_total_bytes         78560 non-null int64
video_total_bytes                78560 non-null int64
social_ntwrking_bytes            78560 non-null int64
cloud_computing_total_bytes      78560 non-null int64
web_security_total_bytes         78560 non-null int64
gaming_total_bytes               78560 non-null int64
health_total_bytes               78560 non-null int64
communication_total_bytes        78560 non-null int64
file_sharing_total_bytes         78560 non-null int64
remote_access_total_bytes        78560 non-null int64
photo_sharing_total_bytes        78560 non-null int64
software_dwnld_total_bytes       78560 non-null int64
marketplace_total_bytes          78560 non-null int64
storage_services_total_bytes     78560 non-null int64
audio_total_bytes                78560 non-null int64
location_services_total_bytes    78560 non-null int64
presence_total_bytes             78560 non-null int64
advertisement_total_bytes        78560 non-null int64
system_total_bytes               78560 non-null int64
voip_total_bytes                 78560 non-null int64
speedtest_total_bytes            78560 non-null int64
email_total_bytes                78560 non-null int64
weather_total_bytes              78560 non-null int64
media_total_bytes                78560 non-null int64
mms_total_bytes                  78560 non-null int64
others_total_bytes               78560 non-null int64
beam_direction                   78560 non-null int64
cell_range                       78560 non-null int64
tilt                             78560 non-null int64
Congestion_Type                  78560 non-null int64
dtypes: int64(38)
memory usage: 22.8 MB

In [50]:
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
train1, test1 = train_test_split(train, test_size=0.3)

In [51]:
train1.describe()

,cell_name,4G_rat,par_year,par_month,par_day,par_hour,par_min,subscriber_count,web_browsing_total_bytes,video_total_bytes,...,speedtest_total_bytes,email_total_bytes,weather_total_bytes,media_total_bytes,mms_total_bytes,others_total_bytes,beam_direction,cell_range,tilt,Congestion_Type
count,5.499200e+04,54992.000000,54992.0,54992.0,54992.000000,54992.000000,54992.000000,54992.000000,54992.000000,54992.000000,...,54992.000000,54992.000000,54992.000000,54992.000000,54992.000000,54992.000000,54992.000000,54992.000000,54992.000000,54992.000000
mean,2.785381e+09,0.499345,2018.0,12.0,15.468323,11.513166,32.990708,573.360489,8090.513620,8272.994654,...,70.215068,70.868326,70.329084,70.661369,70.481415,69.536423,89.949193,4.489198,3.502018,1.497272
std,1.605987e+09,0.500004,0.0,0.0,8.625761,6.939691,16.545184,1084.326245,19325.821995,19397.751560,...,117.246954,117.662092,116.019823,117.200904,117.388789,115.006611,17.650417,1.711299,1.114899,1.121030
min,1.229660e+05,0.000000,2018.0,12.0,1.000000,0.000000,5.000000,1.000000,3.000000,8.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,60.000000,2.000000,2.000000,0.000000
25%,1.396294e+09,0.000000,2018.0,12.0,8.000000,5.000000,20.000000,72.000000,428.000000,477.000000,...,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,75.000000,3.000000,3.000000,0.000000
50%,2.789033e+09,0.000000,2018.0,12.0,15.000000,12.000000,35.000000,188.000000,1533.000000,1684.500000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,90.000000,4.000000,4.000000,1.000000
75%,4.173017e+09,1.000000,2018.0,12.0,23.000000,18.000000,45.000000,569.000000,6577.750000,6911.250000,...,74.000000,76.000000,75.000000,74.000000,75.000000,75.000000,105.000000,6.000000,4.000000,3.000000
max,5.555540e+09,1.000000,2018.0,12.0,30.000000,23.000000,60.000000,16047.000000,311008.000000,316774.000000,...,1612.000000,1563.000000,1680.000000,1518.000000,1587.000000,1600.000000,120.000000,7.000000,5.000000,3.000000

In [52]:
train=train.drop(['par_year','par_month'],axis=1)

In [53]:
train=train.drop(['cell_name'],axis=1)

In [54]:
train.describe()

,4G_rat,par_day,par_hour,par_min,subscriber_count,web_browsing_total_bytes,video_total_bytes,social_ntwrking_bytes,cloud_computing_total_bytes,web_security_total_bytes,...,speedtest_total_bytes,email_total_bytes,weather_total_bytes,media_total_bytes,mms_total_bytes,others_total_bytes,beam_direction,cell_range,tilt,Congestion_Type
count,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,...,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000,78560.000000
mean,0.499173,15.503831,11.514588,33.061736,571.187131,8091.673002,8293.335871,8358.866204,628.757536,72.102864,...,70.689779,70.987156,70.945481,70.594857,70.719297,69.728182,89.991701,4.492146,3.503055,1.498854
std,0.500002,8.634375,6.934351,16.535863,1080.263507,19145.523831,19462.783122,19498.255773,1255.947419,118.254690,...,118.102336,117.821916,117.134609,117.647164,118.032907,114.619303,17.638370,1.709296,1.115255,1.120077
min,0.000000,1.000000,0.000000,5.000000,1.000000,3.000000,5.000000,7.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,60.000000,2.000000,2.000000,0.000000
25%,0.000000,8.000000,5.000000,20.000000,71.000000,431.000000,471.000000,469.000000,69.000000,14.000000,...,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,75.000000,3.000000,3.000000,0.000000
50%,0.000000,16.000000,12.000000,35.000000,187.000000,1545.500000,1672.500000,1682.000000,189.000000,31.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,90.000000,4.000000,4.000000,1.000000
75%,1.000000,23.000000,18.000000,45.000000,568.000000,6565.000000,6884.250000,7008.500000,593.000000,77.000000,...,75.000000,75.000000,76.000000,74.000000,75.000000,75.000000,105.000000,6.000000,4.000000,3.000000
max,1.000000,30.000000,23.000000,60.000000,16570.000000,311008.000000,331271.000000,303204.000000,18901.000000,1666.000000,...,1612.000000,1563.000000,1680.000000,1661.000000,1611.000000,1600.000000,120.000000,7.000000,5.000000,3.000000

In [21]:
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
array = train.values
X = array[:,0:34]
Y = array[:,34]
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])

[  5.282e-01   1.247e+01   2.381e+00   5.585e+01   1.534e+07   2.409e+08
   2.411e+08   2.412e+08   1.738e+07   1.878e+06   1.824e+06   1.874e+06
   1.253e+08   4.455e+05   4.324e+05   9.790e+05   9.681e+05   7.927e+05
   1.784e+06   8.045e+05   1.857e+06   1.211e+08   1.788e+06   1.840e+06
   1.842e+06   1.856e+06   1.845e+06   1.876e+06   1.829e+06   1.804e+06
   1.743e+06   6.046e+00   6.303e-01   9.155e-01]
[[  315 59012  2266 10614]
 [ 1871   334  4530   135]
 [  887   945 23753  3818]
 [ 8577   494  7956  2114]
 [ 2084  1056  7244   605]]

In [72]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
array = train.values
X1 = array[:,0:34]
Y1 =train['Congestion_Type'].values
print(X1)
print(Y1)
print(len(X1))
print(len(Y1))
rfe = RFE(model, 3)
fit = rfe.fit(X1, Y1)
(print("Num Features: %d" % fit.n_features_,))
(print("Selected Features: %s" % fit.support_,))
(print("Feature Ranking: %s" % fit.ranking_,))

[[  1  15   0 ...,  69   6   2]
 [  1   7  20 ...,  93   7   5]
 [  1   5  16 ...,  77   6   3]
 ...,
 [  1   6   1 ...,  95   4   4]
 [  1   7  21 ...,  73   5   5]
 [  1   8  22 ..., 114   2   5]]
[1 3 0 ..., 1 0 3]
78560
78560

KeyboardInterrupt:

In [57]:
train['Congestion_Type'].value_counts()

3    19771
1    19765
0    19688
2    19336
Name: Congestion_Type, dtype: int64

In [71]:
from pandas import read_csv
from sklearn.decomposition import PCA
array = train.values
X2 = array[:,0:34]
Y2 = array[:,34]
pca = PCA(n_components=3)
fit = pca.fit(X2)
(print("Explained Variance: %s" % fit.explained_variance_ratio_,))
print(fit.components_)

Explained Variance: [ 0.322  0.269  0.265]
[[ -7.845e-08  -1.777e-06  -9.167e-07  -1.618e-06   6.884e-03   4.806e-01
    5.964e-01   6.359e-01   7.317e-03   8.829e-04   8.386e-04   8.673e-04
    6.772e-02   2.136e-04   2.163e-04   4.638e-04   4.478e-04   3.864e-04
    8.483e-04   3.863e-04   8.990e-04   6.444e-02   8.738e-04   8.420e-04
    8.674e-04   8.685e-04   8.797e-04   8.633e-04   8.495e-04   8.611e-04
    8.486e-04  -1.931e-06   3.954e-07  -4.666e-08]
 [ -1.236e-07   2.656e-06   9.305e-08  -6.876e-08  -2.341e-04  -3.683e-01
    8.008e-01  -4.723e-01  -1.041e-03  -4.301e-05  -1.809e-05  -2.128e-05
   -2.713e-03  -1.308e-05  -1.863e-05  -2.749e-05  -1.395e-05  -6.113e-06
   -9.449e-06  -9.645e-06  -7.723e-05  -6.356e-04  -1.598e-05  -5.138e-05
    3.433e-05   2.560e-05   5.510e-06  -3.156e-05  -9.019e-06  -1.860e-05
   -3.541e-05  -4.025e-06  -4.906e-07   1.165e-07]
 [ -4.472e-09   1.445e-06  -2.202e-06  -2.073e-06   9.161e-04   7.939e-01
    6.618e-03  -6.079e-01   1.036e-03   8.830e-05   6.415e-05   7.365e-05
    6.031e-03   3.853e-05   2.487e-05   7.117e-05   8.907e-05   5.839e-05
    1.023e-04   2.631e-05   2.019e-04   9.730e-03  -3.242e-06   1.251e-04
    3.841e-05   1.145e-04   1.453e-04   9.019e-05   1.467e-04   8.945e-05
    1.086e-04   3.926e-06   5.215e-07  -1.993e-07]]

In [73]:
from pandas import read_csv
from sklearn.decomposition import PCA
array = train.values
X2 =[train['web_security_total_bytes'],train['gaming_total_bytes'],train ['health_total_bytes'],train['storage_services_total_bytes'],train ['location_services_total_bytes'],train['advertisement_total_bytes'],train ['system_total_bytes'],train['voip_total_bytes'],train ['speedtest_total_bytes'],train['email_total_bytes'],train['weather_total_bytes'],train ['media_total_bytes'],train['mms_total_bytes'],train ['others_total_bytes']]
Y2 = array[:,34]
pca = PCA(n_components=1)
fit = pca.fit(X2)
(print("Explained Variance: %s" % fit.explained_variance_ratio_,))
print(fit.components_)

Explained Variance: [ 0.08]
[[ 0.001  0.     0.002 ...,  0.003 -0.003  0.001]]

In [80]:
Cdf1 = pd.DataFrame(fit.components_)
print(Cdf1)

      0         1         2         3        4        5         6      \
0  0.001489  0.000399  0.002185  0.001206  0.00527 -0.00414 -0.001828

      7         8         9        ...        78550     78551     78552  \
0 -0.000037  0.003577 -0.001123    ...     0.002048 -0.000734  0.000467

     78553     78554     78555     78556     78557     78558     78559
0  0.00479 -0.005635  0.002796 -0.001884  0.003406 -0.003006  0.000777

[1 rows x 78560 columns]

In [81]:
Cdf1=Cdf1.transpose()
print(Cdf1)

              0
0      0.001489
1      0.000399
2      0.002185
3      0.001206
4      0.005270
5     -0.004140
6     -0.001828
7     -0.000037
8      0.003577
9     -0.001123
10    -0.002888
11    -0.002358
12    -0.007594
13    -0.001876
14    -0.004503
15    -0.000086
16     0.003141
17    -0.003094
18     0.000006
19    -0.002234
20     0.000363
21    -0.008949
22     0.003719
23    -0.000357
24     0.000252
25    -0.000273
26     0.002744
27    -0.000159
28    -0.000104
29     0.003331
...         ...
78530 -0.000063
78531 -0.006933
78532 -0.001570
78533 -0.000406
78534 -0.002806
78535  0.001916
78536 -0.002488
78537 -0.000628
78538 -0.010915
78539 -0.000849
78540 -0.000633
78541 -0.000515
78542  0.003054
78543  0.001424
78544 -0.000211
78545  0.002069
78546  0.006611
78547 -0.000151
78548  0.002005
78549  0.000145
78550  0.002048
78551 -0.000734
78552  0.000467
78553  0.004790
78554 -0.005635
78555  0.002796
78556 -0.001884
78557  0.003406
78558 -0.003006
78559  0.000777

[78560 rows x 1 columns]

In [82]:
train = pd.concat([train,Cdf1],axis=1)

In [83]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78560 entries, 0 to 78559
Data columns (total 36 columns):
4G_rat                           78560 non-null int64
par_day                          78560 non-null int64
par_hour                         78560 non-null int64
par_min                          78560 non-null int64
subscriber_count                 78560 non-null int64
web_browsing_total_bytes         78560 non-null int64
video_total_bytes                78560 non-null int64
social_ntwrking_bytes            78560 non-null int64
cloud_computing_total_bytes      78560 non-null int64
web_security_total_bytes         78560 non-null int64
gaming_total_bytes               78560 non-null int64
health_total_bytes               78560 non-null int64
communication_total_bytes        78560 non-null int64
file_sharing_total_bytes         78560 non-null int64
remote_access_total_bytes        78560 non-null int64
photo_sharing_total_bytes        78560 non-null int64
software_dwnld_total_bytes       78560 non-null int64
marketplace_total_bytes          78560 non-null int64
storage_services_total_bytes     78560 non-null int64
audio_total_bytes                78560 non-null int64
location_services_total_bytes    78560 non-null int64
presence_total_bytes             78560 non-null int64
advertisement_total_bytes        78560 non-null int64
system_total_bytes               78560 non-null int64
voip_total_bytes                 78560 non-null int64
speedtest_total_bytes            78560 non-null int64
email_total_bytes                78560 non-null int64
weather_total_bytes              78560 non-null int64
media_total_bytes                78560 non-null int64
mms_total_bytes                  78560 non-null int64
others_total_bytes               78560 non-null int64
beam_direction                   78560 non-null int64
cell_range                       78560 non-null int64
tilt                             78560 non-null int64
Congestion_Type                  78560 non-null int64
0                                78560 non-null float64
dtypes: float64(1), int64(35)
memory usage: 21.6 MB

In [86]:
train.drop(Cdf1,axis=1)

,4G_rat,par_day,par_hour,par_min,subscriber_count,web_browsing_total_bytes,video_total_bytes,social_ntwrking_bytes,cloud_computing_total_bytes,web_security_total_bytes,...,speedtest_total_bytes,email_total_bytes,weather_total_bytes,media_total_bytes,mms_total_bytes,others_total_bytes,beam_direction,cell_range,tilt,Congestion_Type
0,1,15,0,50,152,315,59012,2266,1034,113,...,10,10,33,46,39,103,69,6,2,1
1,1,7,20,5,54,1871,334,4530,63,29,...,8,22,20,7,10,21,93,7,5,3
2,1,5,16,35,277,887,945,23753,171,18,...,23,14,91,49,147,159,77,6,3,0
3,0,16,21,60,51,8577,494,7956,66,60,...,3,10,63,42,75,35,95,7,2,0
4,1,4,6,60,117,2084,1056,7244,232,59,...,4,67,59,91,197,316,112,3,5,2
5,1,7,14,40,220,219,536,28671,4970,20,...,90,222,228,314,129,212,102,4,2,2
6,0,8,21,40,49,1779,413,398,161,90,...,281,19,19,249,240,18,111,3,4,1
7,1,13,13,30,100,24663,9409,831,4,80,...,14,7,20,35,16,91,116,4,2,3
8,0,4,6,10,1523,1065,1105,102431,255,431,...,26,21,33,315,287,170,119,6,5,2
9,1,13,4,55,3548,162,22189,375,792,230,...,15,464,23,55,51,156,92,2,4,1
10,1,17,6,20,230,282,13162,2235,28,1,...,199,7,19,16,22,22,61,3,2,3
11,0,19,1,45,344,21042,541,7042,286,81,...,155,342,21,157,122,28,62,2,2,1
12,1,6,20,30,90,6589,2305,4936,165,45,...,333,2,894,408,192,421,101,6,5,1
13,1,26,9,30,530,2641,4289,1397,443,97,...,97,66,49,33,9,145,107,2,4,2
14,0,12,5,15,18,1255,1647,2280,2557,20,...,111,372,202,23,6,73,71,6,3,2
15,1,18,18,45,707,466,26546,5835,639,42,...,19,11,6,35,12,2,84,3,4,3
16,0,22,17,10,1840,251,2507,20723,85,21,...,9,12,56,3,129,177,64,5,4,0
17,1,23,18,20,236,20805,25164,2342,39,224,...,279,42,44,25,70,27,109,3,4,1
18,1,3,21,10,81,3790,94,1849,510,8,...,14,10,9,3,10,2,89,2,2,3
19,1,14,5,50,316,10054,440,1193,46,21,...,148,12,16,9,9,35,81,3,3,0
20,0,3,13,40,233,13724,16333,14822,2442,6,...,90,44,34,6,62,165,70,5,5,1
21,1,19,13,45,178,1109,12825,1184,264,13,...,24,729,338,421,9,60,99,4,3,2
22,0,17,21,20,138,244,12650,12785,38,32,...,26,137,9,4,222,15,99,2,5,0
23,0,26,2,15,20,584,101,1691,396,19,...,8,11,7,91,19,15,68,4,5,3
24,1,2,17,10,271,184,447,3056,1393,224,...,75,23,438,64,44,35,110,5,3,2
25,1,19,4,40,181,310,1579,242,142,36,...,40,42,19,17,36,39,70,3,3,3
26,0,7,1,50,237,491,736,784,753,4,...,51,71,7,9,147,3,98,7,2,3
27,1,26,22,55,2024,1982,324,1762,1659,61,...,9,49,24,10,13,11,113,3,5,0
28,0,1,7,40,2678,645,619,324,93,37,...,66,143,21,9,57,21,84,2,3,2
29,1,4,4,30,423,102,2254,31848,97,232,...,26,134,74,138,105,55,86,7,5,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78530,1,3,23,50,42,11457,212,430,50,10,...,18,5,1,9,6,9,60,3,3,3
78531,1,27,0,20,128,22302,16589,1784,210,35,...,347,50,10,98,43,1,77,6,3,2
78532,0,26,20,30,5657,47864,100,5435,17,584,...,16,208,59,286,13,402,72,3,4,2
78533,1,24,19,60,44,1795,490,40,199,3,...,15,6,112,10,15,103,88,4,2,3
78534,1,7,8,50,292,63,3392,184,74,20,...,13,43,67,317,18,384,84,5,3,0
78535,1,30,15,60,23,911,446,1158,48,5,...,10,16,86,3,31,25,111,6,2,3
78536,0,18,20,30,46,500,2314,1771,592,38,...,153,10,40,76,11,36,115,5,5,1
78537,1,14,1,35,637,312,136,907,893,31,...,14,12,71,30,20,0,80,2,5,3
78538,1,18,15,5,273,16363,6974,282,1700,102,...,250,363,32,829,102,43,111,3,5,2
78539,1,7,5,50,1073,15382,12303,28597,13,117,...,1,55,17,25,23,25,114,4,2,1
78540,1,6,14,10,21,1768,117,1993,68,2,...,54,5,22,10,5,21,78,4,4,3
78541,1,5,21,10,39,5940,245,14198,25,24,...,80,34,48,5,72,121,89,4,3,0
78542,1,28,15,40,66,2468,34500,610,960,320,...,1,26,6,10,48,7,73,7,2,1
78543,0,7,6,10,153,515,973,2310,48,22,...,58,16,58,96,133,8,112,5,2,0
78544,0,17,14,40,407,2214,436,1448,273,7,...,15,14,5,8,6,5,116,2,5,3
78545,0,30,4,55,36,7458,198,1932,202,14,...,74,163,15,4,193,54,113,7,5,0
78546,1,17,1,50,2766,113636,2106,949,60,44,...,44,161,5,69,486,639,111,5,4,1
78547,1,2,23,35,45,1088,6926,134,99,37,...,32,1,7,36,7,19,92,5,4,3
78548,1,28,1,30,5316,86,2552,1786,214,577,...,28,82,10,178,112,276,65,5,3,1
78549,0,7,22,10,77,1523,334,237,63,25,...,13,48,46,5,14,6,71,6,2,3
78550,1,13,11,15,471,16484,990,21270,217,43,...,9,12,11,260,147,64,66,3,3,1
78551,1,4,14,55,23,12278,254,604,52,15,...,28,12,24,13,1,49,98,4,3,3
78552,0,29,15,40,188,390,7662,1775,1351,183,...,136,86,74,5,118,91,78,6,5,1
78553,1,2,9,30,434,980,173,2587,163,65,...,90,51,37,20,47,260,91,7,4,2
78554,0,17,23,50,1538,552,1752,701,77,23,...,117,683,17,103,24,43,102,7,2,1
78555,1,10,19,5,430,650,36800,13831,425,56,...,33,41,12,41,37,200,86,2,2,1
78556,0,2,8,20,57,13583,1017,176,99,33,...,118,135,72,24,55,58,117,5,5,1
78557,1,6,1,35,4921,8388,337,2155,3537,13,...,23,19,39,65,199,22,95,4,4,1
78558,1,7,21,35,233,289,319,146,352,22,...,111,16,13,143,19,32,73,5,5,0
78559,1,8,22,20,17,1033,200,544,151,15,...,11,6,16,21,47,14,114,2,5,3

In [87]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78560 entries, 0 to 78559
Data columns (total 36 columns):
4G_rat                           78560 non-null int64
par_day                          78560 non-null int64
par_hour                         78560 non-null int64
par_min                          78560 non-null int64
subscriber_count                 78560 non-null int64
web_browsing_total_bytes         78560 non-null int64
video_total_bytes                78560 non-null int64
social_ntwrking_bytes            78560 non-null int64
cloud_computing_total_bytes      78560 non-null int64
web_security_total_bytes         78560 non-null int64
gaming_total_bytes               78560 non-null int64
health_total_bytes               78560 non-null int64
communication_total_bytes        78560 non-null int64
file_sharing_total_bytes         78560 non-null int64
remote_access_total_bytes        78560 non-null int64
photo_sharing_total_bytes        78560 non-null int64
software_dwnld_total_bytes       78560 non-null int64
marketplace_total_bytes          78560 non-null int64
storage_services_total_bytes     78560 non-null int64
audio_total_bytes                78560 non-null int64
location_services_total_bytes    78560 non-null int64
presence_total_bytes             78560 non-null int64
advertisement_total_bytes        78560 non-null int64
system_total_bytes               78560 non-null int64
voip_total_bytes                 78560 non-null int64
speedtest_total_bytes            78560 non-null int64
email_total_bytes                78560 non-null int64
weather_total_bytes              78560 non-null int64
media_total_bytes                78560 non-null int64
mms_total_bytes                  78560 non-null int64
others_total_bytes               78560 non-null int64
beam_direction                   78560 non-null int64
cell_range                       78560 non-null int64
tilt                             78560 non-null int64
Congestion_Type                  78560 non-null int64
0                                78560 non-null float64
dtypes: float64(1), int64(35)
memory usage: 21.6 MB

0        0.001489
1        0.000399
2        0.002185
3        0.001206
4        0.005270
5       -0.004140
6       -0.001828
7       -0.000037
8        0.003577
9       -0.001123
10      -0.002888
11      -0.002358
12      -0.007594
13      -0.001876
14      -0.004503
15      -0.000086
16       0.003141
17      -0.003094
18       0.000006
19      -0.002234
20       0.000363
21      -0.008949
22       0.003719
23      -0.000357
24       0.000252
25      -0.000273
26       0.002744
27      -0.000159
28      -0.000104
29       0.003331
           ...
78530   -0.000063
78531   -0.006933
78532   -0.001570
78533   -0.000406
78534   -0.002806
78535    0.001916
78536   -0.002488
78537   -0.000628
78538   -0.010915
78539   -0.000849
78540   -0.000633
78541   -0.000515
78542    0.003054
78543    0.001424
78544   -0.000211
78545    0.002069
78546    0.006611
78547   -0.000151
78548    0.002005
78549    0.000145
78550    0.002048
78551   -0.000734
78552    0.000467
78553    0.004790
78554   -0.005635
78555    0.002796
78556   -0.001884
78557    0.003406
78558   -0.003006
78559    0.000777
Name: 0, Length: 78560, dtype: float64

In [91]:
train=train.rename(columns={0:'Cdf'})

In [92]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78560 entries, 0 to 78559
Data columns (total 36 columns):
4G_rat                           78560 non-null int64
par_day                          78560 non-null int64
par_hour                         78560 non-null int64
par_min                          78560 non-null int64
subscriber_count                 78560 non-null int64
web_browsing_total_bytes         78560 non-null int64
video_total_bytes                78560 non-null int64
social_ntwrking_bytes            78560 non-null int64
cloud_computing_total_bytes      78560 non-null int64
web_security_total_bytes         78560 non-null int64
gaming_total_bytes               78560 non-null int64
health_total_bytes               78560 non-null int64
communication_total_bytes        78560 non-null int64
file_sharing_total_bytes         78560 non-null int64
remote_access_total_bytes        78560 non-null int64
photo_sharing_total_bytes        78560 non-null int64
software_dwnld_total_bytes       78560 non-null int64
marketplace_total_bytes          78560 non-null int64
storage_services_total_bytes     78560 non-null int64
audio_total_bytes                78560 non-null int64
location_services_total_bytes    78560 non-null int64
presence_total_bytes             78560 non-null int64
advertisement_total_bytes        78560 non-null int64
system_total_bytes               78560 non-null int64
voip_total_bytes                 78560 non-null int64
speedtest_total_bytes            78560 non-null int64
email_total_bytes                78560 non-null int64
weather_total_bytes              78560 non-null int64
media_total_bytes                78560 non-null int64
mms_total_bytes                  78560 non-null int64
others_total_bytes               78560 non-null int64
beam_direction                   78560 non-null int64
cell_range                       78560 non-null int64
tilt                             78560 non-null int64
Congestion_Type                  78560 non-null int64
Cdf                              78560 non-null float64
dtypes: float64(1), int64(35)
memory usage: 21.6 MB

In [93]:
from pandas import read_csv
from sklearn.decomposition import PCA
array = train.values
X2 =[train['web_browsing_total_bytes'],train['video_total_bytes'],train['social_ntwrking_bytes']]
Y2 = array[:,34]
pca = PCA(n_components=1)
fit = pca.fit(X2)
(print("Explained Variance: %s" % fit.explained_variance_ratio_,))
print(fit.components_)

Explained Variance: [ 0.503]
[[  8.918e-03  -4.536e-04  -1.848e-03 ...,  -7.387e-04   1.625e-05
   -8.909e-05]]

In [95]:
Cdf2 = pd.DataFrame(fit.components_)
Cdf2=Cdf2.transpose()
train = pd.concat([train,Cdf2],axis=1)

In [96]:
train=train.rename(columns={0:'Cdf2'})
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78560 entries, 0 to 78559
Data columns (total 37 columns):
4G_rat                           78560 non-null int64
par_day                          78560 non-null int64
par_hour                         78560 non-null int64
par_min                          78560 non-null int64
subscriber_count                 78560 non-null int64
web_browsing_total_bytes         78560 non-null int64
video_total_bytes                78560 non-null int64
social_ntwrking_bytes            78560 non-null int64
cloud_computing_total_bytes      78560 non-null int64
web_security_total_bytes         78560 non-null int64
gaming_total_bytes               78560 non-null int64
health_total_bytes               78560 non-null int64
communication_total_bytes        78560 non-null int64
file_sharing_total_bytes         78560 non-null int64
remote_access_total_bytes        78560 non-null int64
photo_sharing_total_bytes        78560 non-null int64
software_dwnld_total_bytes       78560 non-null int64
marketplace_total_bytes          78560 non-null int64
storage_services_total_bytes     78560 non-null int64
audio_total_bytes                78560 non-null int64
location_services_total_bytes    78560 non-null int64
presence_total_bytes             78560 non-null int64
advertisement_total_bytes        78560 non-null int64
system_total_bytes               78560 non-null int64
voip_total_bytes                 78560 non-null int64
speedtest_total_bytes            78560 non-null int64
email_total_bytes                78560 non-null int64
weather_total_bytes              78560 non-null int64
media_total_bytes                78560 non-null int64
mms_total_bytes                  78560 non-null int64
others_total_bytes               78560 non-null int64
beam_direction                   78560 non-null int64
cell_range                       78560 non-null int64
tilt                             78560 non-null int64
Congestion_Type                  78560 non-null int64
Cdf                              78560 non-null float64
Cdf2                             78560 non-null float64
dtypes: float64(2), int64(35)
memory usage: 22.2 MB

In [102]:
from pandas import read_csv
from sklearn.decomposition import PCA
array = train.values
X2 =[train ['presence_total_bytes'],train['communication_total_bytes']]
Y2 = array[:,34]
pca = PCA(n_components=1)
fit = pca.fit(X2)
(print("Explained Variance: %s" % fit.explained_variance_ratio_,))
print(fit.components_)
Cdf3 = pd.DataFrame(fit.components_)
Cdf3=Cdf3.transpose()
train = pd.concat([train,Cdf3],axis=1)
train=train.rename(columns={0:'Cdf3'})
train.info()

Explained Variance: [ 1.]
[[  3.432e-04   2.801e-05   3.217e-03 ...,   3.771e-06   4.762e-04
   -3.009e-04]]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78560 entries, 0 to 78559
Data columns (total 38 columns):
4G_rat                           78560 non-null int64
par_day                          78560 non-null int64
par_hour                         78560 non-null int64
par_min                          78560 non-null int64
subscriber_count                 78560 non-null int64
web_browsing_total_bytes         78560 non-null int64
video_total_bytes                78560 non-null int64
social_ntwrking_bytes            78560 non-null int64
cloud_computing_total_bytes      78560 non-null int64
web_security_total_bytes         78560 non-null int64
gaming_total_bytes               78560 non-null int64
health_total_bytes               78560 non-null int64
communication_total_bytes        78560 non-null int64
file_sharing_total_bytes         78560 non-null int64
remote_access_total_bytes        78560 non-null int64
photo_sharing_total_bytes        78560 non-null int64
software_dwnld_total_bytes       78560 non-null int64
marketplace_total_bytes          78560 non-null int64
storage_services_total_bytes     78560 non-null int64
audio_total_bytes                78560 non-null int64
location_services_total_bytes    78560 non-null int64
presence_total_bytes             78560 non-null int64
advertisement_total_bytes        78560 non-null int64
system_total_bytes               78560 non-null int64
voip_total_bytes                 78560 non-null int64
speedtest_total_bytes            78560 non-null int64
email_total_bytes                78560 non-null int64
weather_total_bytes              78560 non-null int64
media_total_bytes                78560 non-null int64
mms_total_bytes                  78560 non-null int64
others_total_bytes               78560 non-null int64
beam_direction                   78560 non-null int64
cell_range                       78560 non-null int64
tilt                             78560 non-null int64
Congestion_Type                  78560 non-null int64
Cdf                              78560 non-null float64
Cdf2                             78560 non-null float64
Cdf3                             78560 non-null float64
dtypes: float64(3), int64(35)
memory usage: 22.8 MB

In [103]:
from pandas import read_csv
from sklearn.decomposition import PCA
array = train.values
X2 =[train['photo_sharing_total_bytes'],train['software_dwnld_total_bytes']]
Y2 = array[:,34]
pca = PCA(n_components=1)
fit = pca.fit(X2)
(print("Explained Variance: %s" % fit.explained_variance_ratio_,))
print(fit.components_)
Cdf4 = pd.DataFrame(fit.components_)
Cdf4=Cdf4.transpose()
train = pd.concat([train,Cdf4],axis=1)
train=train.rename(columns={0:'Cdf4'})

Explained Variance: [ 1.]
[[-0.001 -0.     0.    ...,  0.     0.002 -0.001]]

In [104]:
train.head()

,4G_rat,par_day,par_hour,par_min,subscriber_count,web_browsing_total_bytes,video_total_bytes,social_ntwrking_bytes,cloud_computing_total_bytes,web_security_total_bytes,...,mms_total_bytes,others_total_bytes,beam_direction,cell_range,tilt,Congestion_Type,Cdf,Cdf2,Cdf3,Cdf4
0,1,15,0,50,152,315,59012,2266,1034,113,...,39,103,69,6,2,1,0.001489,0.008918,0.000343,-0.001355
1,1,7,20,5,54,1871,334,4530,63,29,...,10,21,93,7,5,3,0.000399,-0.000454,0.000028,-0.000000
2,1,5,16,35,277,887,945,23753,171,18,...,147,159,77,6,3,0,0.002185,-0.001848,0.003217,0.000136
3,0,16,21,60,51,8577,494,7956,66,60,...,75,35,95,7,2,0,0.001206,-0.001199,-0.000528,0.004065
4,1,4,6,60,117,2084,1056,7244,232,59,...,197,316,112,3,5,2,0.005270,-0.000578,0.000096,-0.000994

In [105]:
from pandas import read_csv
from sklearn.decomposition import PCA
array = train.values
X2 =[train['file_sharing_total_bytes'],train['remote_access_total_bytes']]
Y2 = array[:,34]
pca = PCA(n_components=1)
fit = pca.fit(X2)
(print("Explained Variance: %s" % fit.explained_variance_ratio_,))
print(fit.components_)
Cdf5 = pd.DataFrame(fit.components_)
Cdf5=Cdf5.transpose()
train = pd.concat([train,Cdf5],axis=1)
train=train.rename(columns={0:'Cdf5'})

Explained Variance: [ 1.]
[[-0.002 -0.    -0.    ..., -0.001  0.001 -0.   ]]

In [106]:
from pandas import read_csv
from sklearn.decomposition import PCA
array = train.values
X2 =[train['marketplace_total_bytes'], train['audio_total_bytes']]
Y2 = array[:,34]
pca = PCA(n_components=1)
fit = pca.fit(X2)
(print("Explained Variance: %s" % fit.explained_variance_ratio_,))
print(fit.components_)
Cdf6 = pd.DataFrame(fit.components_)
Cdf6=Cdf6.transpose()
train = pd.concat([train,Cdf6],axis=1)
train=train.rename(columns={0:'Cdf6'})

Explained Variance: [ 1.]
[[-0.002 -0.001  0.    ..., -0.01  -0.001  0.002]]

In [107]:
train2=train.drop(['web_security_total_bytes','gaming_total_bytes','health_total_bytes','storage_services_total_bytes','location_services_total_bytes','advertisement_total_bytes','system_total_bytes','voip_total_bytes','speedtest_total_bytes','email_total_bytes','weather_total_bytes','media_total_bytes','mms_total_bytes','others_total_bytes','web_browsing_total_bytes','video_total_bytes','social_ntwrking_bytes','presence_total_bytes','communication_total_bytes','photo_sharing_total_bytes','software_dwnld_total_bytes','file_sharing_total_bytes','remote_access_total_bytes','marketplace_total_bytes','audio_total_bytes'],axis=1)

In [108]:
train2.head()

,4G_rat,par_day,par_hour,par_min,subscriber_count,cloud_computing_total_bytes,beam_direction,cell_range,tilt,Congestion_Type,Cdf,Cdf2,Cdf3,Cdf4,Cdf5,Cdf6
0,1,15,0,50,152,1034,69,6,2,1,0.001489,0.008918,0.000343,-0.001355,-0.001501,-0.001780
1,1,7,20,5,54,63,93,7,5,3,0.000399,-0.000454,0.000028,-0.000000,-0.000322,-0.001001
2,1,5,16,35,277,171,77,6,3,0,0.002185,-0.001848,0.003217,0.000136,-0.000429,0.000167
3,0,16,21,60,51,66,95,7,2,0,0.001206,-0.001199,-0.000528,0.004065,0.000858,-0.004340
4,1,4,6,60,117,232,112,3,5,2,0.005270,-0.000578,0.000096,-0.000994,-0.007825,0.001614

In [109]:
label = train2['Congestion_Type']
train3=train2.drop(['Congestion_Type'],axis=1)

In [111]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
train3, label, test_size=0.33, random_state=42)
from xgboost import XGBClassifier
xgb=XGBClassifier()
xgb.fit(X_train,y_train)
y_pred=xgb.predict(X_test)

ModuleNotFoundError: No module named 'xgboost'